/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Guilherme Góis
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRadio = new javax.swing.ButtonGroup();
        imgFuncao = new javax.swing.JLabel();
        radio1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        radio2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtC = new javax.swing.JTextField();
        formulaGeral2 = new javax.swing.JLabel();
        txt1 = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        txt3 = new javax.swing.JLabel();
        txt4 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        formulaGeral1 = new javax.swing.JLabel();
        txt5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        setSize(new java.awt.Dimension(0, 0));

        imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/padrão.png"))); // NOI18N

        grupoRadio.add(radio1);
        radio1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        radio1.setText("1º Grau");
        radio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Calculadora de Funções");

        grupoRadio.add(radio2);
        radio2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        radio2.setText("2º Grau");
        radio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel3.setText("A");

        txtA.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel4.setText("B");

        txtB.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel5.setText("C");

        txtC.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        formulaGeral2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        txt1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        txt2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        txt3.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        txt4.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        btnCalcular.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        formulaGeral1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        txt5.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(radio1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radio2)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(formulaGeral2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(formulaGeral1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txt3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCalcular)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(imgFuncao)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgFuncao)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radio1)
                            .addComponent(radio2))
                        .addGap(7, 7, 7)
                        .addComponent(formulaGeral1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(formulaGeral2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(btnCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio2ActionPerformed
        // TODO add your handling code here:
        txtC.setEnabled(true);
        formulaGeral1.setText("Fórmula Geral: f(x) = Ax² + Bx + C");
        formulaGeral2.setText("{a, b, c e R | a ≠ 0}");
    }//GEN-LAST:event_radio2ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        if (txtA.getText().isEmpty() == true) {
            txtA.setText("0");
        }
        if (txtB.getText().isEmpty() == true) {
            txtB.setText("0");
        }
        if (txtC.getText().isEmpty() == true) {
            txtC.setText("0");
        }
      
        float a = Float.parseFloat(txtA.getText());
        float b = Float.parseFloat(txtB.getText());
        float c = Float.parseFloat(txtC.getText());
             
        if (radio1.isSelected()) {
            float xZero = ((-b)/a);
            
            if (a == 0 && b == 0) {
                txt1.setText("A = 0 e B = 0 → A reta é igual ao eixo X");
                imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aZbZ.png")));
            }
            
            if (a == 0 && b > 0) {
                txt1.setText("A = 0 → A reta é uma constante paralela ao eixo X");
                txt2.setText("B > 0 → A constante está acima do eixo X");
                imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aZbP.png")));
            }
            
            if (a == 0 && b < 0) {
                txt1.setText("A = 0 → A reta é uma constante paralela ao eixo X");
                txt2.setText("B > 0 → A constante está abaixo do eixo X");
                imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aZbN.png")));
            }
            
            if (a > 0 && b == 0) {
                txt1.setText("A > 0 → A reta é crescente");
                txt2.setText("B = 0 → A reta cruza os eixos X e Y no mesmo ponto");
                txt3.setText("Raiz da função ("+xZero+",0.0)");
                imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aPbZ.png")));
            }
            
            if (a > 0 && b > 0) {
                txt1.setText("A > 0 → A reta é crescente");
                txt2.setText("B > 0 → A reta cruza o eixo Y acima do eixo X");
                txt3.setText("Raiz da função ("+xZero+",0.0)");
                imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aPbP.png")));
            }
            
            if (a > 0 && b < 0) {
                txt1.setText("A > 0 → A reta é crescente");
                txt2.setText("B < 0 → A reta cruza o eixo Y abaixo do eixo X");
                txt3.setText("Raiz da função ("+xZero+",0.0)");
                imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aPbN.png")));
            }
            
            if (a < 0 && b == 0) {
                txt1.setText("A < 0 → A reta é decrescente");
                txt2.setText("B = 0 → A reta cruza os eixos X e Y no mesmo ponto");
                txt3.setText("Raiz da função ("+xZero+",0.0)");
                imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aNbZ.png")));
            }
            
            if (a < 0 && b > 0) {
                txt1.setText("A < 0 → A reta é decrescente");
                txt2.setText("B > 0 → A reta cruza o eixo Y acima do eixo X");
                txt3.setText("Raiz da função ("+xZero+",0.0)");
                imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aNbP.png")));
            }
            
            if (a < 0 && b < 0) {
                txt1.setText("A < 0 → A reta é decrescente");
                txt2.setText("B < 0 → A reta cruza o eixo Y abaixo do eixo X");
                txt3.setText("Raiz da função ("+xZero+",0.0)");
                imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aNbN.png")));
            }
        }
        
        if (radio2.isSelected()) {
            double delta = (Math.pow(b,2)) - (4 * a * c);
            double x1 = Math.round(((-b) + (Math.sqrt(delta))) / (2 * a));
            double x2 = Math.round(((-b)-(Math.sqrt(delta))) / (2 * a));
            double xVertice = Math.round((-b) / (2 * a));
            double yVertice = Math.round((-delta) / (4 * a));
                 
                    
            if (a == 0) {
                txt1.setText("A não pode ser igual à zero");
                imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/padrão.png")));
            }
            else {
                if (a > 0 && b == 0 && c > 0) {
                    txt1.setText("A > 0 → Parábola positiva. Tendo o Vertice como ponto mínimo");
                    txt2.setText("B = 0 → Vertice está no ponto zero do eixo X");
                    txt3.setText("C > 0 → Parábola cruza o eixo Y acima do eixo X");
                    txt4.setText("Coordenadas do Vértice ("+xVertice+","+yVertice+") Δ = "+delta);
                    if (delta < 0) {
                        txt5.setText("Δ < 0 → A função não possui raízes reais");
                    }
                    if (delta > 0) {
                        txt5.setText("Δ > 0 → Duas raízes distintas: x₁="+x1+" e x₂="+x2);
                    }
                    if (delta == 0){
                        txt5.setText("Δ = 0 → Duas raízes iguais: x₁ e x₂="+x2);
                    }
                    imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aPbZcP.png")));
                }
                if (a < 0 && b == 0 && c > 0) {
                    txt1.setText("A < 0 → Parábola negativa. Tendo o Vertice como ponto máximo");
                    txt2.setText("B = 0 → Vertice está no ponto zero do eixo X");
                    txt3.setText("C > 0 → Parábola cruza o eixo Y acima do eixo X");
                    txt4.setText("Coordenadas do Vértice ("+xVertice+","+yVertice+") Δ = "+delta);
                    if (delta < 0) {
                        txt5.setText("Δ < 0 → A função não possui raízes reais");
                    }
                    if (delta > 0) {
                        txt5.setText("Δ > 0 → Duas raízes distintas: x₁="+x1+" e x₂="+x2);
                    }
                    if (delta == 0){
                        txt5.setText("Δ = 0 → Duas raízes iguais: x₁ e x₂="+x2);
                    }
                    imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aNbZcP.png")));
                }
                if (a > 0 && b == 0 && c < 0) {
                    txt1.setText("A > 0 → Parábola positiva. Tendo o Vertice como ponto mínimo");
                    txt2.setText("B = 0 → Vertice está no ponto zero do eixo X");
                    txt3.setText("C < 0 → Parábola cruza o eixo Y abaixo do eixo X");
                    txt4.setText("Coordenadas do Vértice ("+xVertice+","+yVertice+") Δ = "+delta);
                    if (delta < 0) {
                        txt5.setText("Δ < 0 → A função não possui raízes reais");
                    }
                    if (delta > 0) {
                        txt5.setText("Δ > 0 → Duas raízes distintas: x₁="+x1+" e x₂="+x2);
                    }
                    if (delta == 0){
                        txt5.setText("Δ = 0 → Duas raízes iguais: x₁ e x₂="+x2);
                    }
                    imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aPbZcN.png")));
                }
                if (a < 0 && b == 0 && c < 0) {
                    txt1.setText("A < 0 → Parábola negativa. Tendo o Vertice como ponto máximo");
                    txt2.setText("B = 0 → Vertice está no ponto zero do eixo X");
                    txt3.setText("C < 0 → Parábola cruza o eixo Y abaixo do eixo X");
                    txt4.setText("Coordenadas do Vértice ("+xVertice+","+yVertice+") Δ = "+delta);
                    if (delta < 0) {
                        txt5.setText("Δ < 0 → A função não possui raízes reais");
                    }
                    if (delta > 0) {
                        txt5.setText("Δ > 0 → Duas raízes distintas: x₁="+x1+" e x₂="+x2);
                    }
                    if (delta == 0){
                        txt5.setText("Δ = 0 → Duas raízes iguais: x₁ e x₂="+x2);
                    }
                    imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aNbZcN.png")));
                }
                if (a > 0 && b > 0 && c > 0) {
                    txt1.setText("A > 0 → Parábola positiva. Tendo o Vertice como ponto mínimo");
                    txt2.setText("B > 0 → Parábola cruza o eixo Y na fase crescente");
                    txt3.setText("C > 0 → Parábola cruza o eixo Y acima do eixo X");
                    txt4.setText("Coordenadas do Vértice ("+xVertice+","+yVertice+") Δ = "+delta);
                    if (delta < 0) {
                        txt5.setText("Δ < 0 → A função não possui raízes reais");
                    }
                    if (delta > 0) {
                        txt5.setText("Δ > 0 → Duas raízes distintas: x₁="+x1+" e x₂="+x2);
                    }
                    if (delta == 0){
                        txt5.setText("Δ = 0 → Duas raízes iguais: x₁ e x₂="+x2);
                    }
                    imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aPbPcP.png")));
                }
                if (a < 0 && b > 0 && c > 0) {
                    txt1.setText("A < 0 → Parábola negativa. Tendo o Vertice como ponto máximo");
                    txt2.setText("B > 0 → Parábola cruza o eixo Y na fase crescente");
                    txt3.setText("C > 0 → Parábola cruza o eixo Y acima do eixo X");
                    txt4.setText("Coordenadas do Vértice ("+xVertice+","+yVertice+") Δ = "+delta);
                    if (delta < 0) {
                        txt5.setText("Δ < 0 → A função não possui raízes reais");
                    }
                    if (delta > 0) {
                        txt5.setText("Δ > 0 → Duas raízes distintas: x₁="+x1+" e x₂="+x2);
                    }
                    if (delta == 0){
                        txt5.setText("Δ = 0 → Duas raízes iguais: x₁ e x₂="+x2);
                    }
                    imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aNbPcP.png")));
                }
                if (a > 0 && b > 0 && c < 0) {
                    txt1.setText("A > 0 → Parábola positiva. Tendo o Vertice como ponto mínimo");
                    txt2.setText("B > 0 → Parábola cruza o eixo Y na fase crescente");
                    txt3.setText("C < 0 → Parábola cruza o eixo Y abaixo do eixo X");
                    txt4.setText("Coordenadas do Vértice ("+xVertice+","+yVertice+") Δ = "+delta);
                    if (delta < 0) {
                        txt5.setText("Δ < 0 → A função não possui raízes reais");
                    }
                    if (delta > 0) {
                        txt5.setText("Δ > 0 → Duas raízes distintas: x₁="+x1+" e x₂="+x2);
                    }
                    if (delta == 0){
                        txt5.setText("Δ = 0 → Duas raízes iguais: x₁ e x₂="+x2);
                    }
                    imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aPbPcN.png")));
                }
                if (a < 0 && b > 0 && c < 0) {
                    txt1.setText("A < 0 → Parábola negativa. Tendo o Vertice como ponto máximo");
                    txt2.setText("B > 0 → Parábola cruza o eixo Y na fase crescente");
                    txt3.setText("C < 0 → Parábola cruza o eixo Y abaixo do eixo X");
                    txt4.setText("Coordenadas do Vértice ("+xVertice+","+yVertice+") Δ = "+delta);
                    if (delta < 0) {
                        txt5.setText("Δ < 0 → A função não possui raízes reais");
                    }
                    if (delta > 0) {
                        txt5.setText("Δ > 0 → Duas raízes distintas: x₁="+x1+" e x₂="+x2);
                    }
                    if (delta == 0){
                        txt5.setText("Δ = 0 → Duas raízes iguais: x₁ e x₂="+x2);
                    }
                    imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aNbPcN.png")));
                }
                if (a > 0 && b < 0 && c > 0) {
                    txt1.setText("A > 0 → Parábola positiva. Tendo o Vertice como ponto mínimo");
                    txt2.setText("B < 0 → Parábola cruza o eixo Y na fase decrescente");
                    txt3.setText("C > 0 → Parábola cruza o eixo Y acima do eixo X");
                    txt4.setText("Coordenadas do Vértice ("+xVertice+","+yVertice+") Δ = "+delta);
                    if (delta < 0) {
                        txt5.setText("Δ < 0 → A função não possui raízes reais");
                    }
                    if (delta > 0) {
                        txt5.setText("Δ > 0 → Duas raízes distintas: x₁="+x1+" e x₂="+x2);
                    }
                    if (delta == 0){
                        txt5.setText("Δ = 0 → Duas raízes iguais: x₁ e x₂="+x2);
                    }
                    imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aPbNcP.png")));
                }
                if (a < 0 && b < 0 && c > 0) {
                    txt1.setText("A < 0 → Parábola negativa. Tendo o Vertice como ponto máximo");
                    txt2.setText("B < 0 → Parábola cruza o eixo Y na fase decrescente");
                    txt3.setText("C > 0 → Parábola cruza o eixo Y acima do eixo X");
                    txt4.setText("Coordenadas do Vértice ("+xVertice+","+yVertice+") Δ = "+delta);
                    if (delta < 0) {
                        txt5.setText("Δ < 0 → A função não possui raízes reais");
                    }
                    if (delta > 0) {
                        txt5.setText("Δ > 0 → Duas raízes distintas: x₁="+x1+" e x₂="+x2);
                    }
                    if (delta == 0){
                        txt5.setText("Δ = 0 → Duas raízes iguais: x₁ e x₂="+x2);
                    }
                    imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aNbNcP.png")));
                }
                if (a > 0 && b < 0 && c < 0) {
                    txt1.setText("A > 0 → Parábola positiva. Tendo o Vertice como ponto mínimo");
                    txt2.setText("B < 0 → Parábola cruza o eixo Y na fase decrescente");
                    txt3.setText("C < 0 → Parábola cruza o eixo Y abaixo do eixo X");
                    txt4.setText("Coordenadas do Vértice ("+xVertice+","+yVertice+") Δ = "+delta);
                    if (delta < 0) {
                        txt5.setText("Δ < 0 → A função não possui raízes reais");
                    }
                    if (delta > 0) {
                        txt5.setText("Δ > 0 → Duas raízes distintas: x₁="+x1+" e x₂="+x2);
                    }
                    if (delta == 0){
                        txt5.setText("Δ = 0 → Duas raízes iguais: x₁ e x₂="+x2);
                    }
                    imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aPbNcN.png")));
                }
                if (a < 0 && b < 0 && c < 0) {
                    txt1.setText("A < 0 → Parábola negativa. Tendo o Vertice como ponto máximo");
                    txt2.setText("B < 0 → Parábola cruza o eixo Y na fase decrescente");
                    txt3.setText("C < 0 → Parábola cruza o eixo Y abaixo do eixo X");
                    txt4.setText("Coordenadas do Vértice ("+xVertice+","+yVertice+") Δ = "+delta);
                    if (delta < 0) {
                        txt5.setText("Δ < 0 → A função não possui raízes reais");
                    }
                    if (delta > 0) {
                        txt5.setText("Δ > 0 → Duas raízes distintas: x₁="+x1+" e x₂="+x2);
                    }
                    if (delta == 0){
                        txt5.setText("Δ = 0 → Duas raízes iguais: x₁ e x₂="+x2);
                    }
                    imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aNbNcN.png")));
                }
                if (a > 0 && b > 0 && c == 0) {
                    txt1.setText("A > 0 → Parábola positiva. Tendo o Vertice como ponto mínimo");
                    txt2.setText("B > 0 → Parábola cruza o eixo Y na fase crescente");
                    txt3.setText("C = 0 → Vertice está no ponto zero do eixo Y");
                    txt4.setText("Coordenadas do Vértice ("+xVertice+","+yVertice+") Δ = "+delta);
                    if (delta < 0) {
                        txt5.setText("Δ < 0 → A função não possui raízes reais");
                    }
                    if (delta > 0) {
                        txt5.setText("Δ > 0 → Duas raízes distintas: x₁="+x1+" e x₂="+x2);
                    }
                    if (delta == 0){
                        txt5.setText("Δ = 0 → Duas raízes iguais: x₁ e x₂="+x2);
                    }
                    imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aPbPcZ.png")));
                }
                if (a < 0 && b < 0 && c == 0) {
                    txt1.setText("A < 0 → Parábola negativa. Tendo o Vertice como ponto máximo");
                    txt2.setText("B < 0 → Parábola cruza o eixo Y na fase decrescente");
                    txt3.setText("C = 0 → Vertice está no ponto zero do eixo Y");
                    txt4.setText("Coordenadas do Vértice ("+xVertice+","+yVertice+") Δ = "+delta);
                    if (delta < 0) {
                        txt5.setText("Δ < 0 → A função não possui raízes reais");
                    }
                    if (delta > 0) {
                        txt5.setText("Δ > 0 → Duas raízes distintas: x₁="+x1+" e x₂="+x2);
                    }
                    if (delta == 0){
                        txt5.setText("Δ = 0 → Duas raízes iguais: x₁ e x₂="+x2);
                    }
                    imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aNbNcZ.png")));
                }
                if (a > 0 && b < 0 && c == 0) {
                    txt1.setText("A > 0 → Parábola positiva. Tendo o Vertice como ponto mínimo");
                    txt2.setText("B < 0 → Parábola cruza o eixo Y na fase decrescente");
                    txt3.setText("C = 0 → Vertice está no ponto zero do eixo Y");
                    txt4.setText("Coordenadas do Vértice ("+xVertice+","+yVertice+") Δ = "+delta);
                    if (delta < 0) {
                        txt5.setText("Δ < 0 → A função não possui raízes reais");
                    }
                    if (delta > 0) {
                        txt5.setText("Δ > 0 → Duas raízes distintas: x₁="+x1+" e x₂="+x2);
                    }
                    if (delta == 0){
                        txt5.setText("Δ = 0 → Duas raízes iguais: x₁ e x₂="+x2);
                    }
                    imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aPbNcZ.png")));
                }
                if (a < 0 && b > 0 && c == 0) {
                    txt1.setText("A < 0 → Parábola negativa. Tendo o Vertice como ponto máximo");
                    txt2.setText("B > 0 → Parábola cruza o eixo Y na fase crescente");
                    txt3.setText("C = 0 → Vertice está no ponto zero do eixo Y");
                    txt4.setText("Coordenadas do Vértice ("+xVertice+","+yVertice+") Δ = "+delta);
                    if (delta < 0) {
                        txt5.setText("Δ < 0 → A função não possui raízes reais");
                    }
                    if (delta > 0) {
                        txt5.setText("Δ > 0 → Duas raízes distintas: x₁="+x1+" e x₂="+x2);
                    }
                    if (delta == 0){
                        txt5.setText("Δ = 0 → Duas raízes iguais: x₁ e x₂="+x2);
                    }
                    imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aNbPcZ.png")));
                }
                if (a > 0 && b == 0 && c == 0) {
                    txt1.setText("A > 0 → Parábola positiva. Tendo o Vertice como ponto mínimo");
                    txt2.setText("B = 0 → Vertice está no ponto zero do eixo X");
                    txt3.setText("C = 0 → Vertice está no ponto zero do eixo Y");
                    txt4.setText("Coordenadas do Vértice ("+xVertice+","+yVertice+") Δ = "+delta);
                    if (delta < 0) {
                        txt5.setText("Δ < 0 → A função não possui raízes reais");
                    }
                    if (delta > 0) {
                        txt5.setText("Δ > 0 → Duas raízes distintas: x₁="+x1+" e x₂="+x2);
                    }
                    if (delta == 0){
                        txt5.setText("Δ = 0 → Duas raízes iguais: x₁ e x₂="+x2);
                    }
                    imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aPbZcZ.png")));
                }
                if (a < 0 && b == 0 && c == 0) {
                    txt1.setText("A < 0 → Parábola negativa. Tendo o Vertice como ponto máximo");
                    txt2.setText("B = 0 → Vertice está no ponto zero do eixo X");
                    txt3.setText("C = 0 → Vertice está no ponto zero do eixo Y");
                    txt4.setText("Coordenadas do Vértice ("+xVertice+","+yVertice+") Δ = "+delta);
                    if (delta < 0) {
                        txt5.setText("Δ < 0 → A função não possui raízes reais");
                    }
                    if (delta > 0) {
                        txt5.setText("Δ > 0 → Duas raízes distintas: x₁="+x1+" e x₂="+x2);
                    }
                    if (delta == 0){
                        txt5.setText("Δ = 0 → Duas raízes iguais: x₁ e x₂="+x2);
                    }
                    imgFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aNbZcZ.png")));
                }
            }
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void radio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1ActionPerformed
        // TODO add your handling code here:
        txtC.setEnabled(false);
        formulaGeral1.setText("Fórmula Geral: f(x) = Ax + B");
        formulaGeral2.setText("{a, b e R}");
    }//GEN-LAST:event_radio1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel formulaGeral1;
    private javax.swing.JLabel formulaGeral2;
    private javax.swing.ButtonGroup grupoRadio;
    private javax.swing.JLabel imgFuncao;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt4;
    private javax.swing.JLabel txt5;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtC;
    // End of variables declaration//GEN-END:variables
}
